import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormGroup, FormControl, ReactiveFormsModule } from '@angular/forms';
import { ClientSideMultipleSelectionConfig, ClientSideSingleSelectionConfig, SelectedFilterDisplayValuesType, SelectedFilterDisplayValueType, ServerSideMultipleSelectionConfig, ServerSideSingleSelectionConfig, TisSearchAndSelectDropdownModule } from 'tis-search-and-select-dropdown';

@Component({
  selector: 'app-root',
  imports: [CommonModule, ReactiveFormsModule, TisSearchAndSelectDropdownModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'tis-ng-search-and-select-dropdown';
  form!: FormGroup;
  options1: any[] = [
    {
      "id": "628",
      "orgId": "367",
      "companyId": "7",
      "projectId": "4",
      "propertyTypeId": "175",
      "buildingPhaseId": "199",
      "unitNumber": "4801",
      "ownershipRatio": "50.00",
      "area": "50.00",
      "descriptionEn": "",
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1730346066208",
      "updatedAt": "1734926808636",
      "updatedBy": "32646",
      "displaySeqNum": null,
      "houseNumber": "187/1",
      "thirdPartyIntegration": {
        "homeId": "676408d03c993498bb0bd647"
      },
      "seqNo": 1,
      "bimData": null,
      "bimResidenceId": null,
      "lastSyncTime": null,
      "bimLocationData": null,
      "projectName": "EI8HTEEN SEVEN",
      "buildingName": "EI8HTEEN SEVEN"
    },
    {
      "id": "512",
      "orgId": "367",
      "companyId": "7",
      "projectId": "3",
      "propertyTypeId": "168",
      "buildingPhaseId": "166",
      "unitNumber": "2801",
      "ownershipRatio": "261.50",
      "area": "261.00",
      "descriptionEn": "",
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1729832251556",
      "updatedAt": "1745569029553",
      "updatedBy": "32314",
      "displaySeqNum": null,
      "houseNumber": "189/1",
      "thirdPartyIntegration": {
        "homeId": "67d78c74fed0ec2034081ac9"
      },
      "seqNo": 1,
      "bimData": {
        "active": true,
        "remark": "3A",
        "houseId": "189/1",
        "createBy": 1,
        "updateBy": 1,
        "createTime": "2024-09-18T10:52:24.523",
        "unitNumber": "2801",
        "updateTime": "2024-09-18T10:52:24.523",
        "ResidenceID": 1,
        "ResidenceAuthFloor": [
          {
            "seqNo": 22,
            "floorID": 151,
            "floorName": "28",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 362,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L28-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 367,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L28-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.323",
                "locationID": 368,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L28-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS2"
              }
            ],
            "servicemindFloorID": "298"
          },
          {
            "seqNo": 23,
            "floorID": 150,
            "floorName": "27",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 354,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L27-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 360,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L27-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 361,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L27-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS2"
              }
            ],
            "servicemindFloorID": "433"
          },
          {
            "seqNo": 24,
            "floorID": 149,
            "floorName": "26",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.31",
                "locationID": 346,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L26-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 352,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L26-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 353,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L26-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS2"
              }
            ],
            "servicemindFloorID": "434"
          },
          {
            "seqNo": 25,
            "floorID": 121,
            "floorName": "G",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 312,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L1-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 318,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-RS1"
              }
            ],
            "servicemindFloorID": "430"
          },
          {
            "seqNo": 26,
            "floorID": 119,
            "floorName": "B1",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 310,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB1-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 309,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS1"
              }
            ],
            "servicemindFloorID": "431"
          },
          {
            "seqNo": 28,
            "floorID": 117,
            "floorName": "B3",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.277",
                "locationID": 300,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-LB3-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-R1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 307,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB3-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 306,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB3-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS1"
              }
            ],
            "servicemindFloorID": "432"
          }
        ]
      },
      "bimResidenceId": "1",
      "lastSyncTime": "1745569029553",
      "bimLocationData": [
        {
          "active": true,
          "zoneID": 6,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.277",
          "locationID": 300,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 312,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 362,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 354,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.31",
          "locationID": 346,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-R1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 367,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 360,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 352,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS1"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.323",
          "locationID": 368,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 361,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 353,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 307,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 310,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 309,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 306,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 318,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-RS1"
        }
      ],
      "projectName": "ONE89 wireless",
      "buildingName": "ONE89 wireless"
    },
    {
      "id": "513",
      "orgId": "367",
      "companyId": "7",
      "projectId": "3",
      "propertyTypeId": "170",
      "buildingPhaseId": "166",
      "unitNumber": "2805",
      "ownershipRatio": "218.12",
      "area": "218.12",
      "descriptionEn": null,
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1729832251556",
      "updatedAt": "1745569029553",
      "updatedBy": "32314",
      "displaySeqNum": null,
      "houseNumber": "189/2",
      "thirdPartyIntegration": {
        "homeId": "6417e25ce28e350884005c50"
      },
      "seqNo": 1,
      "bimData": {
        "active": true,
        "remark": "3C",
        "houseId": "189/2",
        "createBy": 1,
        "updateBy": 1,
        "createTime": "2024-09-18T10:52:24.697",
        "unitNumber": "2805",
        "updateTime": "2024-09-18T10:52:24.697",
        "ResidenceID": 2,
        "ResidenceAuthFloor": [
          {
            "seqNo": 22,
            "floorID": 151,
            "floorName": "28",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 364,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L28-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.323",
                "locationID": 368,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L28-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 367,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L28-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS1"
              }
            ],
            "servicemindFloorID": "298"
          },
          {
            "seqNo": 23,
            "floorID": 150,
            "floorName": "27",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 357,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L27-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 361,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L27-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 360,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L27-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS1"
              }
            ],
            "servicemindFloorID": "433"
          },
          {
            "seqNo": 24,
            "floorID": 149,
            "floorName": "26",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.31",
                "locationID": 349,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L26-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 353,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L26-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 352,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L26-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS1"
              }
            ],
            "servicemindFloorID": "434"
          },
          {
            "seqNo": 25,
            "floorID": 121,
            "floorName": "G",
            "locations": [
              {
                "active": true,
                "zoneID": 10,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 318,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-RS1"
              },
              {
                "active": true,
                "zoneID": 17,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 315,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L1-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-R5"
              }
            ],
            "servicemindFloorID": "430"
          },
          {
            "seqNo": 26,
            "floorID": 119,
            "floorName": "B1",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 310,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB1-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 309,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS1"
              }
            ],
            "servicemindFloorID": "431"
          },
          {
            "seqNo": 28,
            "floorID": 117,
            "floorName": "B3",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 307,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB3-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 306,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB3-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS1"
              },
              {
                "active": true,
                "zoneID": 17,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.283",
                "locationID": 303,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-LB3-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-R5"
              }
            ],
            "servicemindFloorID": "432"
          }
        ]
      },
      "bimResidenceId": "2",
      "lastSyncTime": "1745569029553",
      "bimLocationData": [
        {
          "active": true,
          "zoneID": 11,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 307,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 310,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 306,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 309,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 318,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-RS1"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.283",
          "locationID": 303,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 315,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.31",
          "locationID": 349,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 357,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 364,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-R5"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.323",
          "locationID": 368,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 361,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 353,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 352,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 360,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 367,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS1"
        }
      ],
      "projectName": "ONE89 wireless",
      "buildingName": "ONE89 wireless"
    }
  ];

  options2: any[] = [];
  options3: any[] = [];
  options4: any[] = [];
  options5: any[] = [];

  options1Data: any;
  options2Data: any;
  options3Data: any;
  options4Data: any;

  config = {
    unitId: <ServerSideSingleSelectionConfig>{
      // uri: '/service-management/common/get-units',
      // method: 'POST',
      // limit: 50,
      isSearchable: true,
      isAllOption: true,
      setFirstOption: true,
      ifLengthOnlyOne: true,
      isEnableRefreshMode: false,
      additionalName: {
        keys: ['unitNumber', 'buildingName', 'projectName'],
        separators: [' | ', ' | ', ' | ']
      }
    },
    singleClientSideSelect: <ClientSideSingleSelectionConfig>{
      uri: 'https://api.freeapi.app/api/v1/public/randomusers',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      dataValueKey: 'data.data',
      hint: {
        msg: 'This is hint for example'
      }
    },
    multipleClientSideSelect: <ClientSideMultipleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      hint: {
        label: 'Note',
        msg: 'This is note for example'
      }
    },
    singleServerSideSelect: <ServerSideSingleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      hint: {
        color: 'green',
        label: 'Note',
        msg: 'This is note for example with customize color'
      }
    },
    multipleServerSideSelect: <ServerSideMultipleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      createNew: {
        label: "Click here to add new.",
        color: 'green',
        clickBtn: this.createNew.bind(this)
      }
    },
    singleClientSideSelectWithTags: <ClientSideSingleSelectionConfig>{
      uri: 'https://mocki.io/v1/307d639d-b36e-4507-ba02-fc2dfe39fb25',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: false,
      isEnableRefreshMode: false,
      badge: {
        key: 'residentTypes',
        classConditionList: [
          { key: 1, value: "Owner", class: 'tis-badge-outline-primary' },
          { key: 2, value: "Resident", class: 'tis-badge-outline-success' },
          { key: 3, value: "Tenant", class: 'tis-badge-outline-accent' },
        ]
      }
    }
  }

  ngOnInit() {
    this.form = new FormGroup({
      singleClientSideSelect: new FormControl('*'),
      multipleClientSideSelect: new FormControl('*'),
      singleServerSideSelect: new FormControl('*'),
      multipleServerSideSelect: new FormControl(null),
      singleClientSideSelectWithTags: new FormControl(null),
    });
  }

  setOptionFirstData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options1Data = values;
  }

  setOptionSecondData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options2Data = values;
  }

  setOptionThirdData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options3Data = values;
  }

  setOptionFourthData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options4Data = values;
  }

  createNew(){
    window.open('https://www.google.com/', '_blank');
  }
}
