import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormGroup, FormControl, ReactiveFormsModule } from '@angular/forms';
import { ClientSideMultipleSelectionConfig, ClientSideSingleSelectionConfig, SelectedFilterDisplayValuesType, SelectedFilterDisplayValueType, ServerSideMultipleSelectionConfig, ServerSideSingleSelectionConfig, TisSearchAndSelectDropdownModule } from 'tis-search-and-select-dropdown';

@Component({
  selector: 'app-root',
  imports: [CommonModule, ReactiveFormsModule, TisSearchAndSelectDropdownModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'tis-ng-search-and-select-dropdown';
  form!: FormGroup;
  options1: any[] = [
    {
      "id": "628",
      "orgId": "367",
      "companyId": "7",
      "projectId": "4",
      "propertyTypeId": "175",
      "buildingPhaseId": "199",
      "unitNumber": "4801",
      "ownershipRatio": "50.00",
      "area": "50.00",
      "descriptionEn": "",
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1730346066208",
      "updatedAt": "1734926808636",
      "updatedBy": "32646",
      "displaySeqNum": null,
      "houseNumber": "187/1",
      "thirdPartyIntegration": {
        "homeId": "676408d03c993498bb0bd647"
      },
      "seqNo": 1,
      "bimData": null,
      "bimResidenceId": null,
      "lastSyncTime": null,
      "bimLocationData": null,
      "projectName": "EI8HTEEN SEVEN",
      "buildingName": "EI8HTEEN SEVEN"
    },
    {
      "id": "512",
      "orgId": "367",
      "companyId": "7",
      "projectId": "3",
      "propertyTypeId": "168",
      "buildingPhaseId": "166",
      "unitNumber": "2801",
      "ownershipRatio": "261.50",
      "area": "261.00",
      "descriptionEn": "",
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1729832251556",
      "updatedAt": "1745569029553",
      "updatedBy": "32314",
      "displaySeqNum": null,
      "houseNumber": "189/1",
      "thirdPartyIntegration": {
        "homeId": "67d78c74fed0ec2034081ac9"
      },
      "seqNo": 1,
      "bimData": {
        "active": true,
        "remark": "3A",
        "houseId": "189/1",
        "createBy": 1,
        "updateBy": 1,
        "createTime": "2024-09-18T10:52:24.523",
        "unitNumber": "2801",
        "updateTime": "2024-09-18T10:52:24.523",
        "ResidenceID": 1,
        "ResidenceAuthFloor": [
          {
            "seqNo": 22,
            "floorID": 151,
            "floorName": "28",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 362,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L28-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 367,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L28-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.323",
                "locationID": 368,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L28-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS2"
              }
            ],
            "servicemindFloorID": "298"
          },
          {
            "seqNo": 23,
            "floorID": 150,
            "floorName": "27",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 354,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L27-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 360,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L27-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 361,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L27-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS2"
              }
            ],
            "servicemindFloorID": "433"
          },
          {
            "seqNo": 24,
            "floorID": 149,
            "floorName": "26",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.31",
                "locationID": 346,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L26-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 352,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L26-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 353,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L26-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS2"
              }
            ],
            "servicemindFloorID": "434"
          },
          {
            "seqNo": 25,
            "floorID": 121,
            "floorName": "G",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 312,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-L1-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-R1"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 318,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-RS1"
              }
            ],
            "servicemindFloorID": "430"
          },
          {
            "seqNo": 26,
            "floorID": 119,
            "floorName": "B1",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 310,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB1-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 309,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS1"
              }
            ],
            "servicemindFloorID": "431"
          },
          {
            "seqNo": 28,
            "floorID": 117,
            "floorName": "B3",
            "locations": [
              {
                "active": true,
                "zoneID": 6,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.277",
                "locationID": 300,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "C",
                "locationName": "C3A-LB3-R1",
                "zoneNameThai": "C3A-R1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-R1"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 307,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB3-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 306,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB3-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS1"
              }
            ],
            "servicemindFloorID": "432"
          }
        ]
      },
      "bimResidenceId": "1",
      "lastSyncTime": "1745569029553",
      "bimLocationData": [
        {
          "active": true,
          "zoneID": 6,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.277",
          "locationID": 300,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 312,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 362,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 354,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-R1"
        },
        {
          "active": true,
          "zoneID": 6,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.31",
          "locationID": 346,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-R1",
          "zoneNameThai": "C3A-R1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-R1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 367,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 360,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 352,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS1"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.323",
          "locationID": 368,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 361,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 353,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 307,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 310,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 309,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 306,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 318,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-RS1"
        }
      ],
      "projectName": "ONE89 wireless",
      "buildingName": "ONE89 wireless"
    },
    {
      "id": "513",
      "orgId": "367",
      "companyId": "7",
      "projectId": "3",
      "propertyTypeId": "170",
      "buildingPhaseId": "166",
      "unitNumber": "2805",
      "ownershipRatio": "218.12",
      "area": "218.12",
      "descriptionEn": null,
      "descriptionTh": null,
      "isActive": true,
      "createdBy": "32314",
      "createdAt": "1729832251556",
      "updatedAt": "1745569029553",
      "updatedBy": "32314",
      "displaySeqNum": null,
      "houseNumber": "189/2",
      "thirdPartyIntegration": {
        "homeId": "6417e25ce28e350884005c50"
      },
      "seqNo": 1,
      "bimData": {
        "active": true,
        "remark": "3C",
        "houseId": "189/2",
        "createBy": 1,
        "updateBy": 1,
        "createTime": "2024-09-18T10:52:24.697",
        "unitNumber": "2805",
        "updateTime": "2024-09-18T10:52:24.697",
        "ResidenceID": 2,
        "ResidenceAuthFloor": [
          {
            "seqNo": 22,
            "floorID": 151,
            "floorName": "28",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 364,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L28-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.323",
                "locationID": 368,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L28-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 151,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "28",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.32",
                "locationID": 367,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L28-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L28-RS1"
              }
            ],
            "servicemindFloorID": "298"
          },
          {
            "seqNo": 23,
            "floorID": 150,
            "floorName": "27",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 357,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L27-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 361,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L27-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 150,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "27",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.317",
                "locationID": 360,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L27-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L27-RS1"
              }
            ],
            "servicemindFloorID": "433"
          },
          {
            "seqNo": 24,
            "floorID": 149,
            "floorName": "26",
            "locations": [
              {
                "active": true,
                "zoneID": 17,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.31",
                "locationID": 349,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L26-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-R5"
              },
              {
                "active": true,
                "zoneID": 11,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 353,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-L26-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 149,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "26",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.313",
                "locationID": 352,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L26-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L26-RS1"
              }
            ],
            "servicemindFloorID": "434"
          },
          {
            "seqNo": 25,
            "floorID": 121,
            "floorName": "G",
            "locations": [
              {
                "active": true,
                "zoneID": 10,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 318,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-L1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-RS1"
              },
              {
                "active": true,
                "zoneID": 17,
                "floorID": 121,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "G",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.29",
                "locationID": 315,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-L1-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-L1-R5"
              }
            ],
            "servicemindFloorID": "430"
          },
          {
            "seqNo": 26,
            "floorID": 119,
            "floorName": "B1",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 310,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB1-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 119,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B1",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 309,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB1-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB1-RS1"
              }
            ],
            "servicemindFloorID": "431"
          },
          {
            "seqNo": 28,
            "floorID": 117,
            "floorName": "B3",
            "locations": [
              {
                "active": true,
                "zoneID": 11,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS2",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 307,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Service",
                "locationName": "C3A-LB3-RS2",
                "zoneNameThai": "C3A-RS2",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS2"
              },
              {
                "active": true,
                "zoneID": 10,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-RS1",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.287",
                "locationID": 306,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "Fireman",
                "locationName": "C3A-LB3-RS1",
                "zoneNameThai": "C3A-RS1",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-RS1"
              },
              {
                "active": true,
                "zoneID": 17,
                "floorID": 117,
                "towerID": 2,
                "beaconID": null,
                "zoneName": "C3A-R5",
                "floorName": "B3",
                "projectID": 1,
                "towerName": "C3A",
                "beaconName": null,
                "createTime": "2024-09-17T18:05:30.283",
                "locationID": 303,
                "updateTime": "2024-09-25T10:29:07.673",
                "projectName": "One Bangkok",
                "elevatorName": "A",
                "locationName": "C3A-LB3-R5",
                "zoneNameThai": "C3A-R5",
                "beaconMajorCode": null,
                "beaconMinorCode": null,
                "locationNameThai": "ซี3เอ-LB3-R5"
              }
            ],
            "servicemindFloorID": "432"
          }
        ]
      },
      "bimResidenceId": "2",
      "lastSyncTime": "1745569029553",
      "bimLocationData": [
        {
          "active": true,
          "zoneID": 11,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 307,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 310,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 306,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 119,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "B1",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.287",
          "locationID": 309,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB1-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 318,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-RS1"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 117,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "B3",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.283",
          "locationID": 303,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-LB3-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-LB3-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 121,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "G",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.29",
          "locationID": 315,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L1-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L1-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.31",
          "locationID": 349,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 357,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-R5"
        },
        {
          "active": true,
          "zoneID": 17,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-R5",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 364,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-R5",
          "zoneNameThai": "C3A-R5",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-R5"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.323",
          "locationID": 368,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 361,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS2"
        },
        {
          "active": true,
          "zoneID": 11,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS2",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 353,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS2",
          "zoneNameThai": "C3A-RS2",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS2"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 149,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "26",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.313",
          "locationID": 352,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L26-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L26-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 150,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "27",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.317",
          "locationID": 360,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L27-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L27-RS1"
        },
        {
          "active": true,
          "zoneID": 10,
          "floorID": 151,
          "towerID": 2,
          "beaconID": null,
          "zoneName": "C3A-RS1",
          "floorName": "28",
          "projectID": 1,
          "towerName": "C3A",
          "beaconName": null,
          "createTime": "2024-09-17T18:05:30.32",
          "locationID": 367,
          "updateTime": "2024-09-25T10:29:07.673",
          "projectName": "One Bangkok",
          "locationName": "C3A-L28-RS1",
          "zoneNameThai": "C3A-RS1",
          "beaconMajorCode": null,
          "beaconMinorCode": null,
          "locationNameThai": "ซี3เอ-L28-RS1"
        }
      ],
      "projectName": "ONE89 wireless",
      "buildingName": "ONE89 wireless"
    }
  ];

  options2: any[] = [
      {
          "teamId": "1419",
          "teamName": "BMO-ASID",
          "description": "BMO-ASID",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1636260564275",
          "updatedAt": "1654230975498",
          "orgId": "89",
          "teamCode": "BMO-ASID",
          "disableLogin": false
      },
      {
          "teamId": "826",
          "teamName": "BMO-CLCR",
          "description": "BMO-CLCR",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1654226168607",
          "orgId": "89",
          "teamCode": "BMO-CLCR",
          "disableLogin": false
      },
      {
          "teamId": "822",
          "teamName": "BMO-CUKN",
          "description": "BMO-CUKN",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1687493685590",
          "orgId": "89",
          "teamCode": "BMO-CUKN",
          "disableLogin": false
      },
      {
          "teamId": "1546",
          "teamName": "BMO-DNJJ",
          "description": "BMO-DNJJ",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1653465259822",
          "updatedAt": "1698820395087",
          "orgId": "89",
          "teamCode": "BMO-DNJJ",
          "disableLogin": false
      },
      {
          "teamId": "1421",
          "teamName": "BMO-M103",
          "description": "BMO-M103",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1636261044872",
          "updatedAt": "1653300124742",
          "orgId": "89",
          "teamCode": "BMO-M103",
          "disableLogin": false
      },
      {
          "teamId": "825",
          "teamName": "BMO-MZRT",
          "description": "BMO-MZRT",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1727833099000",
          "orgId": "89",
          "teamCode": "BMO-MZRT",
          "disableLogin": false
      },
      {
          "teamId": "829",
          "teamName": "BMO-NA33",
          "description": "BMO-NA33",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1656555687781",
          "orgId": "89",
          "teamCode": "BMO-NA33",
          "disableLogin": false
      },
      {
          "teamId": "821",
          "teamName": "BMO-NB19",
          "description": "BMO-NB19",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607414589514",
          "updatedAt": "1741923955607",
          "orgId": "89",
          "teamCode": "BMO-NB19",
          "disableLogin": false
      },
      {
          "teamId": "828",
          "teamName": "BMO-NB33",
          "description": "BMO-NB33",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1741253681756",
          "orgId": "89",
          "teamCode": "BMO-NB33",
          "disableLogin": false
      },
      {
          "teamId": "2371",
          "teamName": "BMO-NB39",
          "description": "BMO-NB39",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1695631179261",
          "updatedAt": "1695631201857",
          "orgId": "89",
          "teamCode": "BMO-NB39",
          "disableLogin": false
      },
      {
          "teamId": "1843",
          "teamName": "BMO-NBSL",
          "description": "BMO-NBSL",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1674631757781",
          "updatedAt": "1683689213791",
          "orgId": "89",
          "teamCode": "BMO-NBSL",
          "disableLogin": false
      },
      {
          "teamId": "823",
          "teamName": "BMO-TPRR",
          "description": "BMO-TPRR",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1678436800180",
          "orgId": "89",
          "teamCode": "BMO-TPRR",
          "disableLogin": false
      },
      {
          "teamId": "827",
          "teamName": "BMO-UDBS",
          "description": "BMO-UDBS",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415493000",
          "updatedAt": "1736387364593",
          "orgId": "89",
          "teamCode": "BMO-UDBS",
          "disableLogin": false
      },
      {
          "teamId": "160",
          "teamName": "BMO-UDRV",
          "description": "BMO-UDRV",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1600493026772",
          "updatedAt": "1688982025834",
          "orgId": "89",
          "teamCode": "BMO-UDRV",
          "disableLogin": false
      },
      {
          "teamId": "161",
          "teamName": "ENGINEER",
          "description": "ENGINEER",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1600493047873",
          "updatedAt": "1608647521357",
          "orgId": "89",
          "teamCode": "ENGINEER",
          "disableLogin": false
      },
      {
          "teamId": "887",
          "teamName": "HQ",
          "description": "HEAD OFFICE",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1608645413043",
          "updatedAt": "1737512046879",
          "orgId": "89",
          "teamCode": "HQ",
          "disableLogin": false
      },
      {
          "teamId": "919",
          "teamName": "Senses-Vendors",
          "description": "Senses Vendors",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1608697460280",
          "updatedAt": "1608697587263",
          "orgId": "89",
          "teamCode": "VENDOR",
          "disableLogin": false
      },
      {
          "teamId": "162",
          "teamName": "SUPER ADMIN",
          "description": "SUPER ADMIN",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1600493067267",
          "updatedAt": "1687407408965",
          "orgId": "89",
          "teamCode": "SUPER ADMIN",
          "disableLogin": false
      },
      {
          "teamId": "1579",
          "teamName": "TECH-ANST",
          "description": "TECH-ANST",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1655275759206",
          "updatedAt": "1743060776700",
          "orgId": "89",
          "teamCode": "TECH-ANST",
          "disableLogin": false
      },
      {
          "teamId": "1420",
          "teamName": "TECH-ASID",
          "description": "TECH-ASID",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1636260631855",
          "updatedAt": "1713858966054",
          "orgId": "89",
          "teamCode": "TECH-ASID",
          "disableLogin": false
      },
      {
          "teamId": "837",
          "teamName": "TECH-CLCR",
          "description": "TECH-CLCR",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1737346914275",
          "orgId": "89",
          "teamCode": "TECH-CLCR",
          "disableLogin": false
      },
      {
          "teamId": "832",
          "teamName": "TECH-CUKN",
          "description": "TECH-CUKN",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1726476014024",
          "orgId": "89",
          "teamCode": "TECH-CUKN",
          "disableLogin": false
      },
      {
          "teamId": "1515",
          "teamName": "TECH - CW",
          "description": "TECH - CW",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1652179316503",
          "updatedAt": "1663641972123",
          "orgId": "89",
          "teamCode": "TECH - CW",
          "disableLogin": false
      },
      {
          "teamId": "833",
          "teamName": "TECH-DLCR",
          "description": "TECH-DLCR",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1612165797136",
          "orgId": "89",
          "teamCode": "TECH-DLCR",
          "disableLogin": false
      },
      {
          "teamId": "1547",
          "teamName": "TECH-DNJJ",
          "description": "TECH-DNJJ",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1653465771496",
          "updatedAt": "1736930111911",
          "orgId": "89",
          "teamCode": "TECH-DNJJ",
          "disableLogin": false
      },
      {
          "teamId": "1422",
          "teamName": "TECH-M103",
          "description": "TECH-M103",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1636261140385",
          "updatedAt": "1679041319014",
          "orgId": "89",
          "teamCode": "TECH-M103",
          "disableLogin": false
      },
      {
          "teamId": "836",
          "teamName": "TECH-MZRT",
          "description": "TECH-MZRT",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1721179289923",
          "orgId": "89",
          "teamCode": "TECH-MZRT",
          "disableLogin": false
      },
      {
          "teamId": "840",
          "teamName": "TECH-NA33",
          "description": "TECH-NA33",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1738308810073",
          "orgId": "89",
          "teamCode": "TECH-NA33",
          "disableLogin": false
      },
      {
          "teamId": "2338",
          "teamName": "TECH-NARI",
          "description": "TECH-NARI",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1693295900148",
          "updatedAt": "1743057648541",
          "orgId": "89",
          "teamCode": "TECH-ANARI",
          "disableLogin": false
      },
      {
          "teamId": "830",
          "teamName": "TECH-NB19",
          "description": "TECH-NB19",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1690884767452",
          "orgId": "89",
          "teamCode": "TECH-NB19",
          "disableLogin": false
      },
      {
          "teamId": "839",
          "teamName": "TECH-NB33",
          "description": "TECH-NB33",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1741253448440",
          "orgId": "89",
          "teamCode": "TECH-NB33",
          "disableLogin": false
      },
      {
          "teamId": "1810",
          "teamName": "TECH-NB39",
          "description": "TECH-NB39",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1672907131103",
          "updatedAt": "1700200267321",
          "orgId": "89",
          "teamCode": "TECH-NB39",
          "disableLogin": false
      },
      {
          "teamId": "1811",
          "teamName": "TECH-NBSL",
          "description": "TECH-NBSL",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1672907181092",
          "updatedAt": "1692338315326",
          "orgId": "89",
          "teamCode": "TECH-NBSL",
          "disableLogin": false
      },
      {
          "teamId": "834",
          "teamName": "TECH-TPRR",
          "description": "TECH-TPRR",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1674727959640",
          "orgId": "89",
          "teamCode": "TECH-TPRR",
          "disableLogin": false
      },
      {
          "teamId": "838",
          "teamName": "TECH-UDBS",
          "description": "TECH-UDBS",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1737433842096",
          "orgId": "89",
          "teamCode": "TECH-UDBS",
          "disableLogin": false
      },
      {
          "teamId": "831",
          "teamName": "TECH-UDRV",
          "description": "TECH-UDRV",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1607415525000",
          "updatedAt": "1744857075531",
          "orgId": "89",
          "teamCode": "TECH-UDRV",
          "disableLogin": false
      },
      {
          "teamId": "1657",
          "teamName": "ฺBMO-ANST",
          "description": "ฺBMO-ANST",
          "isActive": true,
          "createdBy": "1188",
          "createdAt": "1663385526849",
          "updatedAt": "1664957409216",
          "orgId": "89",
          "teamCode": "ฺBMO-ANST",
          "disableLogin": false
      }
  ];
  options3: any[] = [];
  options4: any[] = [];
  options5: any[] = [];

  options1Data: any;
  options2Data: any;
  options3Data: any;
  options4Data: any;

  config = {
    unitId: <ServerSideSingleSelectionConfig>{
      // uri: '/service-management/common/get-units',
      // method: 'POST',
      // limit: 50,
      isSearchable: true,
      isAllOption: true,
      setFirstOption: true,
      ifLengthOnlyOne: true,
      isEnableRefreshMode: false,
      additionalName: {
        keys: ['unitNumber', 'buildingName', 'projectName'],
        separators: [' | ', ' | ', ' | ']
      }
    },
    singleClientSideSelect: <ClientSideSingleSelectionConfig>{
      uri: 'https://api.freeapi.app/api/v1/public/randomusers',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      dataValueKey: 'data.data',
      hint: {
        msg: 'This is hint for example'
      }
    },
    multipleClientSideSelect: <ClientSideMultipleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      hint: {
        label: 'Note',
        msg: 'This is note for example'
      }
    },
    singleServerSideSelect: <ServerSideSingleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      hint: {
        color: 'green',
        label: 'Note',
        msg: 'This is note for example with customize color'
      }
    },
    multipleServerSideSelect: <ServerSideMultipleSelectionConfig>{
      uri: 'https://mocki.io/v1/32ff3217-e809-442c-8e63-b4b0a8416325',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: true,
      isEnableRefreshMode: false,
      createNew: {
        label: "Click here to add new.",
        color: 'green',
        clickBtn: this.createNew.bind(this)
      }
    },
    singleClientSideSelectWithTags: <ClientSideSingleSelectionConfig>{
      uri: 'https://mocki.io/v1/307d639d-b36e-4507-ba02-fc2dfe39fb25',
      method: 'GET',
      limit: 100,
      setFirstOption: false,
      isSearchable: true,
      isAllOption: false,
      isEnableRefreshMode: false,
      badge: {
        key: 'residentTypes',
        classConditionList: [
          { key: 1, value: "Owner", class: 'tis-badge-outline-primary' },
          { key: 2, value: "Resident", class: 'tis-badge-outline-success' },
          { key: 3, value: "Tenant", class: 'tis-badge-outline-accent' },
        ]
      }
    }
  }

  ngOnInit() {
    this.form = new FormGroup({
      singleClientSideSelect: new FormControl('*'),
      multipleClientSideSelect: new FormControl('*'),
      singleServerSideSelect: new FormControl('*'),
      multipleServerSideSelect: new FormControl(null),
      singleClientSideSelectWithTags: new FormControl(null),
    });

    // this.form.get('singleClientSideSelect')?.disable();
    // setTimeout(() => {
    //   this.form.get('singleClientSideSelect')?.enable();
    // }, 3000);

    // setTimeout(() => {
    //   this.form.get('multipleClientSideSelect')?.setValue(this.options2?.map(t => t.teamId));
    // }, 1000);
  }

  setOptionFirstData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options1Data = values;
  }

  setOptionSecondData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options2Data = values;
  }

  setOptionThirdData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options3Data = values;
  }

  setOptionFourthData(values: SelectedFilterDisplayValueType | SelectedFilterDisplayValuesType) {
    this.options4Data = values;
  }

  createNew(){
    window.open('https://www.google.com/', '_blank');
  }
}
